apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-welcome
  namespace: welcome
  labels:
    name: welcome-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  welcome-app
    spec:
      containers:
      - image: auliardd/welcome-app:1.0.0
        name:  welcome-app
        resources:
          requests:
            cpu: "25m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "150M"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-welcome
              key: PORT
        # ports:
        # - containerPort:  8000
        #   name:  my-name
        # volumeMounts:
        # - mountPath: /data
        #   name: data
      # volumes:
      #   - name:
      #     value:
      restartPolicy: Always
      imagePullPolicy: Always
      