apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-welcome
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # Acme Provider
    email: your-email@example.com  # Example email
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: gce    # adjust to ingress controller provider nginx/gce or etc.